version: "3"

services:
  e2guardian:
    build: .
    image: vin0x64/e2guardian:latest
    container_name: e2guardian
    ports:
      - "50170:8080/tcp"
      - "50173:8443/tcp"
    restart: unless-stopped
    volumes:
      - './etc:/opt/e2guardian/etc/e2guardian'
      - './ssl:/etc/e2guardian/ssl'
      - './logs:/opt/e2guardian/var/log/e2guardian'
